name: prime-mainnet-10.1.4

include:
  - docker-compose-core.yml
  # - docker-compose-rosetta.yml

secrets:
  # prerequisite for: postgres, dbsync
  postgres_db:
    file: ./secrets/dbsync/postgres_db
  postgres_password:
    file: ./secrets/dbsync/postgres_password
  postgres_user:
    file: ./secrets/dbsync/postgres_user

volumes:
  # required for: prime-relay
  # node-ipc:
  node-db:
  # required for: postgres
  postgres:
  # required for: dbsync
  db-sync-data:
  # required for - wallet-api
  wallet-api-data: